apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: async-course-web
spec:
  secretName: async-course-web
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
    {{- range .Values.ingress.tls }}
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
    {{- end }}